// ============================================================
// PREP LIST — PRINTABLE FORM TEMPLATES
// ============================================================
// The prep list is a FORM, not a live tracker.
// Quantities are auto-calculated from census + recipe baseServings.
// Admin/manager can edit section headers and override quantities.
// Staff print blank copies and fill in by hand.
//
// A single printed sheet contains:
//   Section 1: Today's Prep  (breakfast / lunch / dinner)
//   Section 2: Tomorrow's Freezer Pull  (proteins on next-day menu)
//   Section 3: Manual additions (free-form override rows)
// ============================================================

export type PrepListMeal = 'Breakfast' | 'Lunch' | 'Dinner' | 'All'

// ── Template (admin-editable structure) ───────────────────────────────────────
export interface PrepListTemplate {
  id: string
  /** Display title printed at top of form */
  title: string
  sections: PrepListSection[]
  /** Footer note printed at bottom of every copy */
  footerNote?: string
  lastEditedById: string
  lastEditedAt: string
  createdAt: string
}

export interface PrepListSection {
  id: string
  /** e.g. "Today's Prep", "Freezer Pull — Tomorrow" */
  title: string
  meal: PrepListMeal
  /** Printed sub-heading / instruction below the section title */
  description?: string
  items: PrepListTemplateItem[]
  /** If true, section always appears even if auto-items are empty */
  alwaysShow: boolean
}

export interface PrepListTemplateItem {
  id: string
  order: number
  /** Item name — either auto-populated from menu or manually set */
  itemName: string
  /** Auto-calculated from census + recipe yield */
  calculatedQty?: number
  unit?: string
  /** Admin can override the auto-calculated qty */
  qtyOverride?: number
  /**
   * If true, this row was generated from the menu/recipe system.
   * If false, it was added manually by a manager.
   */
  isAutoGenerated: boolean
  note?: string
}

// ── Generated Instance (what gets printed) ────────────────────────────────────
/**
 * A resolved, ready-to-print prep list for a specific service date.
 * Built at runtime from: template + active menu + census + recipes.
 */
export interface PrepListInstance {
  /** Service date this prep list covers */
  serviceDate: string       // YYYY-MM-DD
  /** Previous day — freezer pull section targets this date */
  freezerPullDate: string   // YYYY-MM-DD
  census: number
  generatedAt: string
  generatedById: string
  sections: PrepListInstanceSection[]
}

export interface PrepListInstanceSection {
  title: string
  meal: PrepListMeal
  description?: string
  items: PrepListInstanceItem[]
}

export interface PrepListInstanceItem {
  itemName: string
  /** Final qty to prep — override ?? calculated ?? blank */
  qty: number | null        // null = blank line for staff to fill
  unit: string
  note?: string
  /** Flags this row for the freezer pull section */
  isFreezerPull: boolean
}
